/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 .\public\models\wheelRims.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/wheelRims.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.179, -0.432, 0.537]} scale={0.398}>
        <group position={[-0.117, 2.206, -2.627]} rotation={[1.279, 0.165, -2.07]} scale={0.069}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.jante} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.chrome} />
        </group>
        <group position={[0, 2.21, 1.72]} rotation={[-Math.PI / 2, 0, Math.PI / 6]} scale={3.451}>
          <mesh geometry={nodes.Object_7.geometry} material={materials.Matte__FF070707__spec} />
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material.030']} />
        </group>
        <group position={[0, 0, 1.7]} rotation={[0.951, -0.789, 0.782]} scale={[0.439, 0.514, 0.514]}>
          <mesh geometry={nodes.Object_10.geometry} material={materials['FER.002']} />
          <mesh geometry={nodes.Object_11.geometry} material={materials['CRBN_JANTE.002']} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.BLACK} />
        </group>
        <group position={[0, 2.185, -0.492]} rotation={[2.462, -0.422, 2.822]} scale={[3.926, 4.599, 4.599]}>
          <mesh geometry={nodes.Object_14.geometry} material={materials.CABON} />
          <mesh geometry={nodes.Object_15.geometry} material={materials['BLACK.001']} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.BLUE} />
          <mesh geometry={nodes.Object_17.geometry} material={materials['CRBN_JANTE.003']} />
        </group>
        <group position={[0, 0, -0.471]} rotation={[2.462, -0.422, 2.822]} scale={[4.589, 5.376, 5.376]}>
          <mesh geometry={nodes.Object_19.geometry} material={materials['Material.055']} />
          <mesh geometry={nodes.Object_20.geometry} material={materials['Material.054']} />
          <mesh geometry={nodes.Object_21.geometry} material={materials['Material.053']} />
          <mesh geometry={nodes.Object_22.geometry} material={materials['CRBN_JANTE.005']} />
        </group>
        <group position={[-0.487, 0, -2.397]} rotation={[0.951, -0.789, 0.782]} scale={[0.2, 0.234, 0.234]}>
          <mesh geometry={nodes.Object_24.geometry} material={materials['pneu.012']} />
          <mesh geometry={nodes.Object_25.geometry} material={materials['PZEO.001']} />
        </group>
        <group position={[-0.682, 0, -4.548]} rotation={[Math.PI / 2, 0, Math.PI / 3]} scale={[1.022, 0.366, 1.022]}>
          <mesh geometry={nodes.Object_27.geometry} material={materials['Material.072']} />
          <mesh geometry={nodes.Object_28.geometry} material={materials['Material.072']} />
          <mesh geometry={nodes.Object_29.geometry} material={materials['Material.071']} />
        </group>
        <group position={[-0.512, 2.834, -4.157]} rotation={[-Math.PI / 2, 0, 0]} scale={2.957}>
          <mesh geometry={nodes.Object_31.geometry} material={materials['CRBN_JANTE.009']} />
          <mesh geometry={nodes.Object_32.geometry} material={materials['Material.082']} />
          <mesh geometry={nodes.Object_33.geometry} material={materials['Material.081']} />
          <mesh geometry={nodes.Object_34.geometry} material={materials['Material.080']} />
        </group>
        <group position={[0.012, 2.061, -5.097]} rotation={[0, -Math.PI / 2, 0]} scale={0.025}>
          <mesh geometry={nodes.Object_42.geometry} material={materials.MetalDark} />
          <mesh geometry={nodes.Object_43.geometry} material={materials.MetalGoldenLogo} />
        </group>
        <mesh geometry={nodes.Object_36.geometry} material={materials['Material.045']} position={[0, 1.946, -4.289]} rotation={[2.531, 0, Math.PI]} scale={[8.682, 10.171, 10.171]} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.etrier} position={[-0.604, 2.875, -5.065]} rotation={[-0.107, Math.PI / 2, 0]} scale={[0.651, 0.651, 0.515]} />
        <mesh geometry={nodes.Object_40.geometry} material={materials['Matte__FF070707__spec_.001']} position={[-0.512, 1.491, -4.6]} rotation={[-Math.PI / 4, 0, 0]} scale={10.972} />
      </group>
    </group>
  )
}

useGLTF.preload('/wheelRims.glb')
